rvm:
  - 1.9.2
  - 1.9.3
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/config.yml.sample config/config.yml
script: "bundle exec rake db:drop db:create db:migrate spec"
notifications:
  email:
    - mail@ssig33.com
